### ISSUE TITLE
Range Calendar outline ring gets cropped in range selection 

### ISSUE THREAD

**Issue by Fercas123** [jpmorganchase/salt-ds#3372]
### Package name(s)

Lab (@salt-ds/lab)

### Description

focus ring gets cropped in range inside range calendar

### Steps to reproduce

in the calendar range example, select a range and navigate trough keyboard

### Expected behavior

the ring should not get cropped

### Operating system

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by joshwooding** [comment]
@mark-tate should this be addressed in your PR?

**Comment by mark-tate** [comment]
Fennel Goal: combine with VQA outstanding items if still exists.
